### ISSUE TITLE
can't install on ubuntu 23.04 because vulkan sdk won't install as it has an resolved dependancies

### ISSUE THREAD

**Issue by davidbuzz** [smumriak/AppKid#2]

**Comment by smumriak** [comment]
Hey @davidbuzz,
Thanks for filing this issue. Indeed vulkan-sdk from Lunarg can not be installed on Ubuntu 23.04 because Lunarg only supports 20.04 and 22.04 (the LTS versions). Good news is you can substitute it with `libvulkan-dev` package. It supplies a couple of versions older version of vulkan dev package, but it will suffice. You will have to remove whatever what was installed from lunarg repo:
`sudo apt remove vulkan-sdk libvulkan1 libvulkan-dev`
and disable lunarg repository completely. 
You also will need  to regenerate `vkthings` to make the project buildable. Just run the following commands before compiling:
```
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/CVulkan/VulkanEnums.h --c-enums
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/CVulkan/VulkanOptionSets.h --c-option-sets
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/Volcano/Utilities/VulkanStructureChainParsing/VulkanStructureConformance.swift --swift-structs
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/Volcano/Enums/VulkanEnums.swift --swift-enums
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/Volcano/OptionSets/VulkanOptionSets.swift --swift-option-sets
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/Volcano/Utilities/VulkanExtensionsNames.swift --swift-extensions
```
Or run task called "vkthings" from VSCode. I'll close this issue after updating readme with these instructions
Have fun!

**Comment by davidbuzz** [comment]
I made a sample Package.swift and main.swift using basically the same code as the README recomends [in a folder structure as swift likes it] , but instead of pulling it from git, I pointed the Package.swift dependancies url to a local folder ../../AppKid where i had cloned and run your above instructions [no errors, just warnings "warning: 'appkid': ignoring broken symlink ..."] , and finally did a 'swift build' .. and got a bunch of build errors...

here's the first three..
... /e1/.build/checkouts/AppKid/Volcano/Sources/Volcano/Utilities/VulkanStructureChainParsing/VulkanStructureConformance.swift:1438:59: error: no type named 'VkImageViewSlicedCreateInfoEXT' in module 'CVulkan'
public typealias VkImageViewSlicedCreateInfoEXT = CVulkan.VkImageViewSlicedCreateInfoEXT
                                                          ^
... /e1/.build/checkouts/AppKid/Volcano/Sources/Volcano/Utilities/VulkanStructureChainParsing/VulkanStructureConformance.swift:1684:47: error: no type named 'VkMemoryMapInfoKHR' in module 'CVulkan'
public typealias VkMemoryMapInfoKHR = CVulkan.VkMemoryMapInfoKHR
                                              ^
... /e1/.build/checkouts/AppKid/Volcano/Sources/Volcano/Utilities/VulkanStructureChainParsing/VulkanStructureConformance.swift:1708:49: error: no type named 'VkMemoryUnmapInfoKHR' in module 'CVulkan'
public typealias VkMemoryUnmapInfoKHR = CVulkan.VkMemoryUnmapInfoKHR

... continues for hundreds of errors..

**Comment by smumriak** [comment]
Yea, that's exactly what I have expected to happen without regenerating those files. Here's some additional context: files VulkanEnums.h, VulkanOptionSets.h, VulkanStructureConformance.swift, VulkanEnums.swift, VulkanOptionSets.swift and VulkanExtensionsNames.swift are generated by a custom tool based on currently installed version of vulkan on the local machine. Because of that whenever there's a difference in those versions there are errors like this. 
For example, VkImageViewSlicedCreateInfoEXT was added to vulkan spec 1.3.242 while libvulkan-dev on ubuntu 23.04 ships 1.3.239, which does not include that.

This generation of things was originally a temporary hack while swift package manager was shaping its plugin API, but I never had time to go back and automate it. So for now in order to get your local build working you still have to re-run this:
```
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/CVulkan/VulkanEnums.h --c-enums
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/CVulkan/VulkanOptionSets.h --c-option-sets
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/Volcano/Utilities/VulkanStructureChainParsing/VulkanStructureConformance.swift --swift-structs
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/Volcano/Enums/VulkanEnums.swift --swift-enums
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/Volcano/OptionSets/VulkanOptionSets.swift --swift-option-sets
swift run --build-path .build vkthings /usr/share/vulkan/registry/vk.xml -o ./Volcano/Sources/Volcano/Utilities/VulkanExtensionsNames.swift --swift-extensions
``` 
from the root of this repository.

I'll land a change that moves this to swiftpm plugin so nobody would ever have to hassle with this.

**Comment by smumriak** [comment]
Actually @davidbuzz scratch all I said in previous comment. Just pull fresh version and it's going to work.

**Comment by davidbuzz** [comment]
readme says that for development libclang-12-dev is needed, but on 23.04, the oldest available is libclang-13-dev

**Comment by davidbuzz** [comment]
after pulling latest code from git, and installing libclang-13-dev and cleaning everything i could an re-running this, i now get only 3  STB errors:
cd ~/AppKid
git pull
git reset --hard origin/main
swift package purge-cache ; swift package reset ; swift package clean ; 
rm -rf .build/
rm -rf ~/.cache/org.swift.swiftpm/
[then all the 'swift run xxx' commands u mentioned above]
swift build --product AppKid

errors:
swift build --product AppKid
Building for debugging...
warning: 'appkid': ignoring broken symlink  ... /AppKid/CairoGraphics/SwiftSTB/Sources/STBImageRead/include/STBImageRead.h
warning: 'appkid': ignoring broken symlink  ... /AppKid/CairoGraphics/SwiftSTB/Sources/STBImageWrite/include/STBImageWrite.h
warning: 'appkid': ignoring broken symlink  ... /AppKid/CairoGraphics/SwiftSTB/Sources/STBImageResize/include/STBImageResize.h
warning: 'appkid': ignoring broken symlink  ... /AppKid/Volcano/Sources/VulkanMemoryAllocatorAdapted/include/VulkanMemoryAllocatorAdaptor.h
 ... /AppKid/CairoGraphics/SwiftSTB/Sources/STBImageRead/STBImageRead.c:2:10: fatal error: 'STBImageRead.h' file not found
#include "STBImageRead.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
 ... /AppKid/CairoGraphics/SwiftSTB/Sources/STBImageWrite/STBImageWrite.c:2:10: fatal error: 'STBImageWrite.h' file not found
#include "STBImageWrite.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
 ... /AppKid/CairoGraphics/SwiftSTB/Sources/STBImageResize/STBImageResize.c:2:10: fatal error: 'STBImageResize.h' file not found
#include "STBImageResize.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
[0/21] Compiling VulkanMemoryAllocatorAdapted VulkanMemoryAllocatorAdapted.cpp

[ i have put ... in the above copy-paste to replace the full-path info that's not relevant ]

**Comment by davidbuzz** [comment]
stb fix:
... aparently stb is in a git submodule that wasn't checked out..
ls -l CairoGraphics/SwiftSTB/Sources/STBImageRead/include/STBImageRead.h
lrwxrwxrwx 1 buzz buzz 38 Jun 29 13:03 CairoGraphics/SwiftSTB/Sources/STBImageRead/include/STBImageRead.h -> ../../../../ThirdParty/stb/stb_image.h
ls -l CairoGraphics/SwiftSTB/Sources/STBImageRead/include/../../../../ThirdParty/stb/
total 0
git submodule init
git submodule update

  Cloning into ' xxx /AppKid/CairoGraphics/ThirdParty/stb'...
  Cloning into ' xxx /AppKid/Volcano/ThirdParty/VulkanMemoryAllocator'...
  Submodule path 'CairoGraphics/ThirdParty/stb': checked out 'af1a5bc352164740c1cc1354942b1c6b72eacb8a'
  Submodule path 'Volcano/ThirdParty/VulkanMemoryAllocator': checked out '413fc4f98812994e295d05491254823a8ba89400'

swift build --product AppKid
...
[503/503] Linking libAppKid.so
Build complete! (19.36s)

**Comment by davidbuzz** [comment]
... but this success is still only building it with a locally checked-out copy, not using it as a package with SPM...
when defined in a Package.swift of a minimal other app [ as derscribed in the README .. wether its using a 'url' pointing to the git repo, and or 'url' pointing to a local-checked-out copy, it still fails with teh same vulcan errors..
[ both of these url choces fail for me with the same vulcan error/s as above ]
// swift-tools-version: 5.8
import PackageDescription

let package = Package(
  name: "MyApp",
  dependencies: [
    .package(
	  //url: "../../AppKid", 
    url: "https://github.com/smumriak/AppKid",  
	  branch: "main"
	),
  ],
  targets: [
    .executableTarget(
      name: "MyApp",
      dependencies: [
        .product(name: "AppKid", package: "AppKid")
      ])
  ]
)
last couple of errors:
 xxx /.build/checkouts/AppKid/Volcano/Sources/Volcano/Utilities/VulkanStructureChainParsing/VulkanStructure.swift:48:9: note: protocol requires property 'pNext' with type 'UnsafeRawPointer?'
    var pNext: UnsafeRawPointer! { get set }
        ^
 xxx /.build/checkouts/AppKid/Volcano/Sources/Volcano/Utilities/VulkanStructureChainParsing/VulkanStructureConformance.swift:4158:1: error: type 'VkSwapchainPresentModesCreateInfoEXT' does not conform to protocol 'VulkanInStructure'
extension VkSwapchainPresentModesCreateInfoEXT: VulkanInStructure {
^
CVulkan.VkSwapchainPresentModesCreateInfoEXT:5:16: note: candidate has non-matching type 'UnsafeMutableRawPointer?'
    public var pNext: UnsafeMutableRawPointer!
               ^
 xxx /.build/checkouts/AppKid/Volcano/Sources/Volcano/Utilities/VulkanStructureChainParsing/VulkanStructureConformance.swift:4158:1: error: type 'VkSwapchainPresentModesCreateInfoEXT' does not conform to protocol 'VulkanChainableStructure'
extension VkSwapchainPresentModesCreateInfoEXT: VulkanInStructure {

:-(

**Comment by smumriak** [comment]
Could you please try to wipe swift package cache?
```
swift package purge-cache
```

**Comment by smumriak** [comment]
> readme says that for development libclang-12-dev is needed, but on 23.04, the oldest available is libclang-13-dev

it's not needed for the framework, it's only needed if you have intention to modify shaders in ContentAnimation

**Comment by smumriak** [comment]
This issue is completely resolved in https://github.com/smumriak/AppKid/commit/b0436abd24444d59e0a03d7d0aa88bdee7a87518
From now on all swift generated files for Vulkan are done using swiftpm plugin

**Comment by smumriak** [comment]
@davidbuzz I've just tried installing the jammy version of Vulkan SDK on 23.04 and it installs without the problem. Please use that, just replace `focal` with `jammy` in apt sources list on your system
also since swiftpm silently added support to resources generation I was able to finish VolcanoSL plugin. After https://github.com/smumriak/AppKid/commit/265f5ddc693fbbb716b313fb134de10c40ec66af installation of libclang is necessary for compilation to work and README lists libclang-15, which should be available on all modern systems

**Comment by smumriak** [comment]
also, unfortunately swift's cache cleaning routine is not extremely stable. sometimes it just fails completely and it is required to remove swift folders under `~/.cache`, particularly `org.swift.foundation.URLCache` and `org.swift.swiftpm`

**Comment by davidbuzz** [comment]
> also, unfortunately swift's cache cleaning routine is not extremely stable. sometimes it just fails completely and it is required to remove swift folders under `~/.cache`, particularly `org.swift.foundation.URLCache` and `org.swift.swiftpm`

..thought i was being pretty thorough on the 'cache clean with my...
```
swift package purge-cache ; swift package reset ; swift package clean ;
rm -rf .build/
rm -rf ~/.cache/org.swift.swiftpm/
```

**Comment by smumriak** [comment]
@davidbuzz did you run update after that?
```
swift package update
```
