### ISSUE TITLE
when following the instructions in the README from section 'Getting started with AppKid in your project' , I am unable to complete the steps.

### ISSUE THREAD

**Issue by davidbuzz** [smumriak/AppKid#3]
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CClang_umbrella.h"
         ^
xxx/MyApp/.build/checkouts/AppKid/Volcano/Sources/CClang/CClang_umbrella.h:20:10: error: 'clang-c/Index.h' file not found
#include <clang-c/Index.h>
         ^
xxx/MyApp/.build/checkouts/AppKid/Volcano/Sources/VolcanoSL/main.swift:8:8: error: could not build C module 'CClang'
import CClang
       ^

**Comment by davidbuzz** [comment]
additional note, my setup currently has 'sudo apt install libvulkan-dev' , but not vulkan-sdk , so perhaps that's why its not working.   both of those are supposed to work according to the readme, so either the readme needs updating to remove this suggestion, or my setup is correct-enough, but still missing something else that needs to be in the readme.

**Comment by smumriak** [comment]
Yea, you need to install libclang **now**
I've mentioned this in the previous issue you've filed
![image](https://github.com/smumriak/AppKid/assets/4306641/b7903fdd-d142-49f7-b418-685cda84a5bd)

**Comment by davidbuzz** [comment]
I get this message *with*  libclang-15-dev already installed, still not sure how to progress past this error.

$sudo apt install libclang-15-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libclang-15-dev is already the newest version (1:15.0.7-3).

MyApp]$ swift build
Building for debugging...
warning: Will not do cross-module incremental builds, priors saved at TimePoint(seconds: 1688511398, nanoseconds: 0)), but the previous build started at TimePoint(seconds: 1688511398, nanoseconds: 13203000), at 'xxx/MyApp/.build/x86_64-unknown-linux-gnu/debug/Volcano.build/master.priors'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CClang_umbrella.h"
         ^
xxx/MyApp/.build/checkouts/AppKid/Volcano/Sources/CClang/CClang_umbrella.h:20:10: error: 'clang-c/Index.h' file not found
#include <clang-c/Index.h>
         ^
xxx/MyApp/.build/checkouts/AppKid/Volcano/Sources/VolcanoSL/main.swift:8:8: error: could not build C module 'CClang'
import CClang
       ^
error: emit-module command failed with exit code 1 (use -v to see invocation)
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CClang_umbrella.h"
         ^
xxx/MyApp/.build/checkouts/AppKid/Volcano/Sources/CClang/CClang_umbrella.h:20:10: error: 'clang-c/Index.h' file not found
#include <clang-c/Index.h>
         ^
xxx/MyApp/.build/checkouts/AppKid/Volcano/Sources/VolcanoSL/main.swift:8:8: error: could not build C module 'CClang'
import CClang
       ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CClang_umbrella.h"
         ^
xxx/MyApp/.build/checkouts/AppKid/Volcano/Sources/CClang/CClang_umbrella.h:20:10: error: 'clang-c/Index.h' file not found
#include <clang-c/Index.h>
         ^
xxx/MyApp/.build/checkouts/AppKid/Volcano/Sources/VolcanoSL/main.swift:8:8: error: could not build C module 'CClang'
import CClang
       ^
[7/336] Emitting module volcanosl

**Comment by smumriak** [comment]
And you even installed the correct pkgconfig? What's the output of 
`pkg-config --cflags clang`?

**Comment by davidbuzz** [comment]
$  pkg-config --cflags clang
-I/usr/lib/llvm-12/include

**Comment by davidbuzz** [comment]
so it looks like I had the -12 from a few days ago when the readme said that ...ok, after re-doing the wget to get the latest version ...
sudo wget -q https://raw.githubusercontent.com/smumriak/AppKid/main/SupportingFiles/clang.pc -O /usr/local/lib/pkgconfig/clang.pc

$pkg-config --cflags clang
-I/usr/lib/llvm-15/include 

.. and then in my demo/example app [ to be sure ] :
    swift package update 
    swift package purge-cache 
    swift package reset 
    swift package clean 
    rm -rf ~/.cache/org.swift.foundation.URLCache/
    rm -rf ~/.cache/org.swift.swiftpm/
    rm -rf .build/
    swift build 
  ..
   swift build
Building for debugging...
[9/9] Linking MyApp
Build complete! (0.62s)

And then, I edit my main.swift, and add :
'import AppKid' 
near the top... and I get..

$ swift build
Building for debugging...
warning: Will not do cross-module incremental builds, priors saved at TimePoint(seconds: 1688529682, nanoseconds: 0)), but the previous build started at TimePoint(seconds: 1688529682, nanoseconds: 343634000), at 'xxx/MyApp/.build/x86_64-unknown-linux-gnu/debug/MyApp.build/master.priors'
error: emit-module command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: missing required module 'cglm'
<unknown>:0: error: missing required module 'cglm'

**Comment by smumriak** [comment]
Throw there `-v` flag to see the verbose output. At least this is something new and unexpected

**Comment by davidbuzz** [comment]
output too long, posted it here:
https://gist.github.com/davidbuzz/bff901576d09a05f4e90efc607577d83

**Comment by smumriak** [comment]
> output too long, posted it here: https://gist.github.com/davidbuzz/bff901576d09a05f4e90efc607577d83

there are no errors in this one. did you pipe output to file? if so you need to pipe both stdout and stderr like so:
```
swift build -v > out.txt 2>&1
```

UPD. just in case, I spawned a fresh 23.04 virtual machine and followed the steps in README:
![image](https://github.com/smumriak/AppKid/assets/4306641/7a6f2a9e-9fb4-4ddb-a464-fafb14f76e54)

**Comment by davidbuzz** [comment]
> there are no errors in this one. 

yes there are , search for 'missing required module'

>did you pipe output to file? 

no, cut-n-pasted from console.

**Comment by davidbuzz** [comment]
i can confirm that installing 'sudo apt install vulkan-sdk'  seems to work, but the other documentation that that has 'libvulkan-dev' in it does not.
this is what [ i think] did it for me:
sudo apt remove shaderc glslc vulkan-sdk 
 sudo apt install -y vulkan-sdk

**Comment by davidbuzz** [comment]
... and to be clear, I still haven't had a single window/display/app/screen render at any point.

**Comment by davidbuzz** [comment]
you know what would be really helpful [to me] ? a separate git repo containing a absolute *minimal* example/demo/minimal app that *uses* AppKid through its Package.swift 
..
	  url: "https://github.com/smumriak/AppKid", 
...
      dependencies: [
        .product(name: "AppKid", package: "AppKid")
      ],
 
 ... and shows a main window, eg Hello works when cloned with git and 'swift run'..
 
 eg..  https://github.com/davidbuzz/AppKidDemo/
 
 ... but one that builds-runs, and opens a window... as mine doesn't.  :-)

**Comment by smumriak** [comment]
So what you've linked builds on your machine, right? After installing vulkan-sdk? Rename your `main.swift` to something else, like `AppDelegate.swift` and uncomment `@main` attribute that you've commented out. Clean local build after that :)

![image](https://github.com/smumriak/AppKid/assets/4306641/272dbdd3-feae-4037-a63b-6d6fe219e1e3)

I assume compiler told you you can not have top level main declaration and `@main` attribute used. In swift if your project provides `main.swift` it is assumed as "the main function", like a script. So your code is essentially no-op, because it declares two classes, never instantiates them and finishes execution.
`@main` attribute tells compiler which type provides explicit "main" function. The common practice is to declare it in protocol extension in the framework. This is how SwiftUI's `App` works, how AppKit, UIKit and other Apple*kit work and how AppKid works.

> a separate git repo containing a absolute minimal example/demo/minimal app that uses AppKid through its Package.swift

Let me make that real quick, that's a very good idea. If you'd like some in-person getting started with swift and whatnot you can message me in Messenger at https://www.facebook.com/smumryak/

UPD. https://github.com/smumriak/AppKidDemo

**Comment by davidbuzz** [comment]
fabulous, thats exactly what I needed, and now works [for me] as described.   I knew i was close. :-)  I'm not sure how to document it...  would a GETTING_STARTED.md  be an appropriate place?

**Comment by davidbuzz** [comment]
closing in favour of https://github.com/smumriak/AppKid/pull/5
